version: '3'
services:
  mine-support-web:
    build: .
    image: mine-support-web
    container_name: mine-support-web
    command: npm run start:watch    
    environment:
      SEND_CLAIM_CONNECTION_STRING: ${SEND_CLAIM_CONNECTION_STRING}
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
