version: '3'
services:
  mine-support-web:
    depends_on: 
      - mine-support-message
    networks: 
      - mine-support 

  mine-support-message:
    container_name: mine-support-message
    image: vromero/activemq-artemis:2.9.0-alpine
    networks:
      - mine-support
    environment:
      ARTEMIS_USERNAME: artemis
      ARTEMIS_PASSWORD: artemis
    ports:
      - "8161:8161"
      - "5672:5672"
    volumes:
      - message-queue-data:/var/lib/artemis/data
      - message-queue-tmp:/var/lib/artemis/tmp
      - message-queue-etc:/var/lib/artemis/etc
      - message-queue-etc-override:/var/lib/artemis/etc-override
      - message-queue-lock:/var/lib/artemis/lock

volumes:
  message-queue-data: {}
  message-queue-tmp: {}
  message-queue-etc: {}
  message-queue-etc-override: {}
  message-queue-lock: {}

networks:
  mine-support:
    external: true
