version: '3'
services:
  mine-support-web:
    build: .
    image: mine-support-web
    container_name: mine-support-web
    command: npm run start:watch    
    environment:
      MESSAGE_HOST: mine-support-message
      MESSAGE_PORT: 5672
      MESSAGE_TRANSPORT: tcp
      CLAIM_MESSAGE_USERNAME: artemis
      CLAIM_MESSAGE_PASSWORD: artemis      
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
