version: '3'
services:
  mine-support-web:
    build: .
    image: mine-support-web
    container_name: mine-support-web
    command: npm run start:watch    
    environment:
      MESSAGE_HOST: ${MESSAGE_HOST}
      CLAIM_MESSAGE_USERNAME: ${CLAIM_MESSAGE_USERNAME}
      CLAIM_MESSAGE_PASSWORD: ${CLAIM_MESSAGE_PASSWORD}      
    ports:
      - "3000:3000"
    volumes:
      - node_modules:/usr/src/app/node_modules
      - .:/usr/src/app

volumes:
  node_modules:
